### ISSUE TITLE
requrements.txt broken

### ISSUE THREAD

**Issue by OliverW10** [thedropbears/pyrapidreact#12]
ERROR: Cannot install -r requirements.txt (line 2), -r requirements.txt (line 3), -r requirements.txt (line 4), -r requirements.txt (line 5) and wpilib~=2022.2.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested wpilib~=2022.2.1
    robotpy-ctre 2022.0.2 depends on wpilib<2023.0.0 and >=2022.2.1.0
    robotpy-navx 2022.0.0 depends on wpilib<2023.0.0 and >=2022.2.1.0
    robotpy-rev 2022.0.0 depends on wpilib<2023.0.0 and >=2022.2.1.0
    robotpy-wpilib-utilities 2020.0.3 depends on wpilib<2021.0.0 and >=2020.1.2.1
    The user requested wpilib~=2022.2.1
    robotpy-ctre 2022.0.2 depends on wpilib<2023.0.0 and >=2022.2.1.0
    robotpy-navx 2022.0.0 depends on wpilib<2023.0.0 and >=2022.2.1.0
    robotpy-rev 2022.0.0 depends on wpilib<2023.0.0 and >=2022.2.1.0
    robotpy-wpilib-utilities 2020.0.2 depends on wpilib<2021.0.0 and >=2020.1.2.1
    The user requested wpilib~=2022.2.1
    robotpy-ctre 2022.0.2 depends on wpilib<2023.0.0 and >=2022.2.1.0
    robotpy-navx 2022.0.0 depends on wpilib<2023.0.0 and >=2022.2.1.0
    robotpy-rev 2022.0.0 depends on wpilib<2023.0.0 and >=2022.2.1.0
    robotpy-wpilib-utilities 2020.0.1 depends on wpilib<2021.0.0 and >=2020.1.2.1
    The user requested wpilib~=2022.2.1
    robotpy-ctre 2022.0.2 depends on wpilib<2023.0.0 and >=2022.2.1.0
    robotpy-navx 2022.0.0 depends on wpilib<2023.0.0 and >=2022.2.1.0
    robotpy-rev 2022.0.0 depends on wpilib<2023.0.0 and >=2022.2.1.0
    robotpy-wpilib-utilities 2020.0.0 depends on wpilib<2021.0.0 and >=2020.1.2.1

**Comment by OliverW10** [comment]
idk why this happened but its not anymore

**Comment by auscompgeek** [comment]
This was fixed in 8ddc78f76c866dc1f1c319fde2bf8fbd3fd23171
